name: sarb
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  - numpy
  - cdo
  - wgrib2
  - pip
  - cartopy
  - seaborn
  - pip:
    - eccodes
    - scipy
    - xarray
    - cfgrib
    - netcdf4
